// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Balance.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0-preview.1.23111.4");

            modelBuilder.Entity("Balance.Storage.Records.AccountRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 808251
                        });
                });

            modelBuilder.Entity("Balance.Storage.Records.AccrualRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Accruals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 808251,
                            Amount = 3206.69m,
                            DateTime = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 808251,
                            Amount = 2708.58m,
                            DateTime = new DateTime(2019, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AccountId = 808251,
                            Amount = 4186.33m,
                            DateTime = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            AccountId = 808251,
                            Amount = 4117.3m,
                            DateTime = new DateTime(2019, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            AccountId = 808251,
                            Amount = 3744.13m,
                            DateTime = new DateTime(2019, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            AccountId = 808251,
                            Amount = 3736.89m,
                            DateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            AccountId = 808251,
                            Amount = 4133.56m,
                            DateTime = new DateTime(2021, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            AccountId = 808251,
                            Amount = 2362.34m,
                            DateTime = new DateTime(2019, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            AccountId = 808251,
                            Amount = 3314.17m,
                            DateTime = new DateTime(2019, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            AccountId = 808251,
                            Amount = 3812.3m,
                            DateTime = new DateTime(2019, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            AccountId = 808251,
                            Amount = 4094.2m,
                            DateTime = new DateTime(2019, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            AccountId = 808251,
                            Amount = 4198.42m,
                            DateTime = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            AccountId = 808251,
                            Amount = 4035.72m,
                            DateTime = new DateTime(2020, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            AccountId = 808251,
                            Amount = 4217.02m,
                            DateTime = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            AccountId = 808251,
                            Amount = 4196.03m,
                            DateTime = new DateTime(2020, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            AccountId = 808251,
                            Amount = 1475.39m,
                            DateTime = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            AccountId = 808251,
                            Amount = 4405.54m,
                            DateTime = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            AccountId = 808251,
                            Amount = 1422.11m,
                            DateTime = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            AccountId = 808251,
                            Amount = 3996.37m,
                            DateTime = new DateTime(2021, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            AccountId = 808251,
                            Amount = 1425.48m,
                            DateTime = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            AccountId = 808251,
                            Amount = 3618.13m,
                            DateTime = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            AccountId = 808251,
                            Amount = 4253.45m,
                            DateTime = new DateTime(2020, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            AccountId = 808251,
                            Amount = 4712.1m,
                            DateTime = new DateTime(2019, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            AccountId = 808251,
                            Amount = 2756.79m,
                            DateTime = new DateTime(2019, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            AccountId = 808251,
                            Amount = 3672.17m,
                            DateTime = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            AccountId = 808251,
                            Amount = 3702.91m,
                            DateTime = new DateTime(2020, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            AccountId = 808251,
                            Amount = 3872.25m,
                            DateTime = new DateTime(2020, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Balance.Storage.Records.HistoryAmountRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccrualId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccrualId");

                    b.ToTable("HistoryAmounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccrualId = 1,
                            Amount = 4176.03m
                        },
                        new
                        {
                            Id = 2,
                            AccrualId = 2,
                            Amount = 6493.68m
                        },
                        new
                        {
                            Id = 3,
                            AccrualId = 3,
                            Amount = 9480.45m
                        },
                        new
                        {
                            Id = 4,
                            AccrualId = 4,
                            Amount = 4612.1m
                        },
                        new
                        {
                            Id = 5,
                            AccrualId = 5,
                            Amount = 4117.3m
                        },
                        new
                        {
                            Id = 6,
                            AccrualId = 6,
                            Amount = 3744.13m
                        },
                        new
                        {
                            Id = 7,
                            AccrualId = 7,
                            Amount = 4393.54m
                        },
                        new
                        {
                            Id = 8,
                            AccrualId = 8,
                            Amount = 0m
                        },
                        new
                        {
                            Id = 9,
                            AccrualId = 9,
                            Amount = 2361.34m
                        },
                        new
                        {
                            Id = 10,
                            AccrualId = 10,
                            Amount = 3314.17m
                        },
                        new
                        {
                            Id = 11,
                            AccrualId = 11,
                            Amount = 3812.3m
                        },
                        new
                        {
                            Id = 12,
                            AccrualId = 12,
                            Amount = 100m
                        },
                        new
                        {
                            Id = 13,
                            AccrualId = 13,
                            Amount = 3872.25m
                        },
                        new
                        {
                            Id = 14,
                            AccrualId = 14,
                            Amount = 4198.42m
                        },
                        new
                        {
                            Id = 15,
                            AccrualId = 15,
                            Amount = 4197.02m
                        },
                        new
                        {
                            Id = 16,
                            AccrualId = 16,
                            Amount = 150m
                        },
                        new
                        {
                            Id = 17,
                            AccrualId = 17,
                            Amount = 4034.72m
                        },
                        new
                        {
                            Id = 18,
                            AccrualId = 18,
                            Amount = 1454.39m
                        },
                        new
                        {
                            Id = 19,
                            AccrualId = 19,
                            Amount = 90m
                        },
                        new
                        {
                            Id = 20,
                            AccrualId = 20,
                            Amount = 1411.11m
                        },
                        new
                        {
                            Id = 21,
                            AccrualId = 21,
                            Amount = 1425.48m
                        },
                        new
                        {
                            Id = 22,
                            AccrualId = 22,
                            Amount = 850m
                        },
                        new
                        {
                            Id = 23,
                            AccrualId = 23,
                            Amount = 8840.63m
                        },
                        new
                        {
                            Id = 24,
                            AccrualId = 24,
                            Amount = 3736.89m
                        },
                        new
                        {
                            Id = 25,
                            AccrualId = 25,
                            Amount = 4243.45m
                        },
                        new
                        {
                            Id = 26,
                            AccrualId = 26,
                            Amount = 3672.17m
                        },
                        new
                        {
                            Id = 27,
                            AccrualId = 27,
                            Amount = 3702.91m
                        });
                });

            modelBuilder.Entity("Balance.Storage.Records.PaymentRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 808251,
                            Amount = 100m,
                            DateTime = new DateTime(2019, 2, 22, 9, 25, 0, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("ded84f45-aa79-4e10-ae1c-9f1ee4062709")
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 808251,
                            Amount = 8840.63m,
                            DateTime = new DateTime(2019, 2, 2, 14, 50, 32, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("ff18a790-f9c3-440c-9f9b-7e085a6531e6")
                        },
                        new
                        {
                            Id = 3,
                            AccountId = 808251,
                            Amount = 4612.1m,
                            DateTime = new DateTime(2019, 3, 15, 21, 6, 10, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("a1a85f99-8e1c-4a70-901e-eab334e3bc12")
                        },
                        new
                        {
                            Id = 4,
                            AccountId = 808251,
                            Amount = 4117.3m,
                            DateTime = new DateTime(2019, 4, 6, 8, 47, 8, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("29bd3151-c2b0-467a-a32c-d7df6ea8a495")
                        },
                        new
                        {
                            Id = 5,
                            AccountId = 808251,
                            Amount = 3744.13m,
                            DateTime = new DateTime(2019, 5, 21, 20, 51, 43, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("d8c1da6b-1cfd-4b5b-bfa7-ff6e553372e4")
                        },
                        new
                        {
                            Id = 6,
                            AccountId = 808251,
                            Amount = 6493.68m,
                            DateTime = new DateTime(2019, 7, 1, 20, 5, 23, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("9291f910-b160-471f-8cdf-56d7dbbf78ba")
                        },
                        new
                        {
                            Id = 7,
                            AccountId = 808251,
                            Amount = 2708.58m,
                            DateTime = new DateTime(2019, 8, 8, 8, 47, 43, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("b5b7c9e5-f2c6-400f-b708-b1b42c9652c5")
                        },
                        new
                        {
                            Id = 8,
                            AccountId = 808251,
                            Amount = 1m,
                            DateTime = new DateTime(2019, 8, 8, 10, 19, 46, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("34168b38-c77c-4474-a440-0f74e980e978")
                        },
                        new
                        {
                            Id = 9,
                            AccountId = 808251,
                            Amount = 2361.34m,
                            DateTime = new DateTime(2019, 9, 10, 21, 45, 30, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("fffe8706-9779-4be0-b836-5b074c779e6a")
                        },
                        new
                        {
                            Id = 10,
                            AccountId = 808251,
                            Amount = 3314.17m,
                            DateTime = new DateTime(2019, 10, 1, 21, 30, 36, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("7cf9e5d2-1a09-400c-a4b4-d5aecc8c760e")
                        },
                        new
                        {
                            Id = 11,
                            AccountId = 808251,
                            Amount = 4034.72m,
                            DateTime = new DateTime(2021, 1, 7, 9, 56, 23, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("6cb33594-dd8a-4d86-9db8-85e7488b80d3")
                        },
                        new
                        {
                            Id = 12,
                            AccountId = 808251,
                            Amount = 1m,
                            DateTime = new DateTime(2021, 1, 13, 12, 45, 1, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("9ec11c18-7e05-41cd-a3cf-8d2d9e4309fb")
                        },
                        new
                        {
                            Id = 13,
                            AccountId = 808251,
                            Amount = 10m,
                            DateTime = new DateTime(2021, 1, 13, 12, 37, 2, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("fb6882bc-a5f3-466c-9655-7d296f2c8103")
                        },
                        new
                        {
                            Id = 14,
                            AccountId = 808251,
                            Amount = 1m,
                            DateTime = new DateTime(2021, 1, 13, 12, 38, 45, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("aaa2ff85-fb86-4794-b53b-5d8f51eb6206")
                        },
                        new
                        {
                            Id = 15,
                            AccountId = 808251,
                            Amount = 10m,
                            DateTime = new DateTime(2020, 7, 24, 16, 35, 32, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("a97c9733-9961-4994-9eef-cd69478040c4")
                        },
                        new
                        {
                            Id = 16,
                            AccountId = 808251,
                            Amount = 10m,
                            DateTime = new DateTime(2020, 7, 8, 10, 51, 53, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("9800b5ee-f0b1-4bdd-863c-2eccf7482ca8")
                        },
                        new
                        {
                            Id = 17,
                            AccountId = 808251,
                            Amount = 1425.48m,
                            DateTime = new DateTime(2020, 7, 3, 14, 5, 58, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("acb7f497-d3d2-44a9-9f41-a80d6bcb4d94")
                        },
                        new
                        {
                            Id = 18,
                            AccountId = 808251,
                            Amount = 10m,
                            DateTime = new DateTime(2020, 5, 27, 11, 3, 47, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("e1281c35-283f-48bc-a4f7-e66af74dee3a")
                        },
                        new
                        {
                            Id = 19,
                            AccountId = 808251,
                            Amount = 10m,
                            DateTime = new DateTime(2020, 5, 21, 12, 12, 2, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("c55c137c-3c89-4aa5-8451-cffbb7828a6f")
                        },
                        new
                        {
                            Id = 20,
                            AccountId = 808251,
                            Amount = 1m,
                            DateTime = new DateTime(2020, 5, 21, 12, 13, 52, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("1b540330-4be2-4369-9944-4710ecc49dd9")
                        },
                        new
                        {
                            Id = 21,
                            AccountId = 808251,
                            Amount = 100m,
                            DateTime = new DateTime(2020, 5, 19, 20, 40, 21, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("e10d8845-dbb6-437e-b47c-657f5225d01d")
                        },
                        new
                        {
                            Id = 22,
                            AccountId = 808251,
                            Amount = 10m,
                            DateTime = new DateTime(2020, 5, 15, 14, 19, 48, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("2bd2da3a-c6ed-463b-9135-159520399804")
                        },
                        new
                        {
                            Id = 23,
                            AccountId = 808251,
                            Amount = 15m,
                            DateTime = new DateTime(2020, 5, 15, 14, 20, 19, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("5721a487-70d6-4fa7-a81a-d9f52002052b")
                        },
                        new
                        {
                            Id = 24,
                            AccountId = 808251,
                            Amount = 1000m,
                            DateTime = new DateTime(2020, 5, 20, 8, 55, 18, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("ff577d1a-6781-46d6-973b-bf4cb703fe3a")
                        },
                        new
                        {
                            Id = 25,
                            AccountId = 808251,
                            Amount = 165m,
                            DateTime = new DateTime(2020, 5, 21, 12, 13, 14, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("f514b40c-095e-4e9b-b3c3-cd4d0774ff95")
                        },
                        new
                        {
                            Id = 26,
                            AccountId = 808251,
                            Amount = 29.39m,
                            DateTime = new DateTime(2020, 5, 15, 14, 21, 9, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("f6f5c6fb-e6ae-473d-bf70-f32e7472d7a6")
                        },
                        new
                        {
                            Id = 27,
                            AccountId = 808251,
                            Amount = 125m,
                            DateTime = new DateTime(2020, 5, 19, 20, 40, 45, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("14f65234-54eb-4ca7-bd46-ec9b9a4ed2dc")
                        },
                        new
                        {
                            Id = 28,
                            AccountId = 808251,
                            Amount = 3812.3m,
                            DateTime = new DateTime(2019, 11, 1, 10, 3, 5, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("c4858527-5edc-45df-a01c-c630901f23bf")
                        },
                        new
                        {
                            Id = 29,
                            AccountId = 808251,
                            Amount = 4094.2m,
                            DateTime = new DateTime(2019, 12, 2, 13, 29, 17, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("e3327b59-4bb5-4a35-a049-45447d7a1a33")
                        },
                        new
                        {
                            Id = 30,
                            AccountId = 808251,
                            Amount = 4198.42m,
                            DateTime = new DateTime(2020, 1, 10, 20, 56, 14, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("992d1d03-7b6b-4d09-8bcc-9061f272d7a5")
                        },
                        new
                        {
                            Id = 31,
                            AccountId = 808251,
                            Amount = 20m,
                            DateTime = new DateTime(2020, 1, 30, 0, 35, 27, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("a67d331a-30a6-4b76-9937-e65a2be876b8")
                        },
                        new
                        {
                            Id = 32,
                            AccountId = 808251,
                            Amount = 4217.02m,
                            DateTime = new DateTime(2020, 2, 1, 12, 33, 7, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("0b4120f3-efa1-4243-9862-e264e3d879c7")
                        },
                        new
                        {
                            Id = 33,
                            AccountId = 808251,
                            Amount = 1411.11m,
                            DateTime = new DateTime(2020, 6, 19, 13, 29, 30, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("81dd2abd-cc90-466d-9442-8853d3c4d64e")
                        },
                        new
                        {
                            Id = 34,
                            AccountId = 808251,
                            Amount = 1m,
                            DateTime = new DateTime(2020, 4, 21, 12, 5, 18, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("d03f927a-6cff-4c27-9b94-958eed4a9f63")
                        },
                        new
                        {
                            Id = 35,
                            AccountId = 808251,
                            Amount = 10m,
                            DateTime = new DateTime(2020, 4, 21, 12, 7, 18, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("69ae0749-c20a-413e-8b13-5a22ce1eb32a")
                        },
                        new
                        {
                            Id = 36,
                            AccountId = 808251,
                            Amount = 10m,
                            DateTime = new DateTime(2020, 4, 21, 12, 4, 32, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("ab8c3615-6e3d-45d9-ba28-47b1d8f6e21c")
                        },
                        new
                        {
                            Id = 37,
                            AccountId = 808251,
                            Amount = 7382.72m,
                            DateTime = new DateTime(2020, 4, 1, 14, 28, 35, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("df2740ec-9436-4271-959f-2c0c2531e8b0")
                        },
                        new
                        {
                            Id = 38,
                            AccountId = 808251,
                            Amount = 3702.91m,
                            DateTime = new DateTime(2020, 11, 18, 19, 32, 30, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("124e2884-a800-4a18-9c55-af95d7dbb29a")
                        },
                        new
                        {
                            Id = 39,
                            AccountId = 808251,
                            Amount = 3598.13m,
                            DateTime = new DateTime(2020, 8, 5, 11, 1, 52, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("a8920cef-5d6a-437f-8ba6-f2591bd18790")
                        },
                        new
                        {
                            Id = 40,
                            AccountId = 808251,
                            Amount = 10m,
                            DateTime = new DateTime(2020, 8, 11, 12, 46, 45, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("c93331fa-175c-491a-9f1b-cf8242a6ab05")
                        },
                        new
                        {
                            Id = 41,
                            AccountId = 808251,
                            Amount = 3672.17m,
                            DateTime = new DateTime(2020, 10, 2, 14, 58, 46, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("71f1eba9-de8e-4599-8ecf-a3149bab1179")
                        },
                        new
                        {
                            Id = 42,
                            AccountId = 808251,
                            Amount = 4243.45m,
                            DateTime = new DateTime(2020, 9, 4, 16, 44, 15, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("82dcf303-1839-42de-aa37-bdb85c603cde")
                        },
                        new
                        {
                            Id = 43,
                            AccountId = 808251,
                            Amount = 3976.37m,
                            DateTime = new DateTime(2021, 4, 9, 22, 46, 4, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("6449bdcb-b5cc-421e-83fa-53fdbd27ea40")
                        },
                        new
                        {
                            Id = 44,
                            AccountId = 808251,
                            Amount = 4179.8m,
                            DateTime = new DateTime(2021, 2, 4, 19, 47, 51, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("6cc291bd-17c2-41f4-9396-32c5293dca58")
                        },
                        new
                        {
                            Id = 45,
                            AccountId = 808251,
                            Amount = 5m,
                            DateTime = new DateTime(2021, 2, 3, 17, 57, 48, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("649458aa-85ad-4809-8155-b8cb34c8e492")
                        },
                        new
                        {
                            Id = 46,
                            AccountId = 808251,
                            Amount = 10m,
                            DateTime = new DateTime(2021, 2, 3, 17, 55, 14, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("dcfa3aa7-c7fb-4a42-8ddf-5e7e063899b4")
                        },
                        new
                        {
                            Id = 47,
                            AccountId = 808251,
                            Amount = 43.54m,
                            DateTime = new DateTime(2021, 2, 3, 17, 53, 23, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("e113d4f9-8b6d-4b51-b144-d0ba3833a77c")
                        },
                        new
                        {
                            Id = 48,
                            AccountId = 808251,
                            Amount = 20m,
                            DateTime = new DateTime(2021, 2, 3, 20, 55, 20, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("7ac3e34d-55e6-45f6-8eb5-274969aa3f95")
                        },
                        new
                        {
                            Id = 49,
                            AccountId = 808251,
                            Amount = 12.2m,
                            DateTime = new DateTime(2021, 2, 3, 20, 50, 2, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("038fb8c2-d7a3-4cf7-a65b-1e7bef26e06c")
                        },
                        new
                        {
                            Id = 50,
                            AccountId = 808251,
                            Amount = 8m,
                            DateTime = new DateTime(2021, 2, 3, 19, 51, 6, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("19eb22bb-4160-48e5-b256-f9c6c183d5b5")
                        },
                        new
                        {
                            Id = 51,
                            AccountId = 808251,
                            Amount = 15m,
                            DateTime = new DateTime(2021, 2, 3, 20, 57, 0, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("b16f527c-f358-413b-bc26-eca3235caddf")
                        },
                        new
                        {
                            Id = 52,
                            AccountId = 808251,
                            Amount = 100m,
                            DateTime = new DateTime(2021, 2, 3, 17, 52, 44, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("ffd741ba-6a79-460e-90ba-aaf834e3d7e0")
                        },
                        new
                        {
                            Id = 53,
                            AccountId = 808251,
                            Amount = 3872.25m,
                            DateTime = new DateTime(2020, 12, 5, 15, 24, 57, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("d9af2afc-658b-4a82-aae6-1973f2bb4992")
                        },
                        new
                        {
                            Id = 54,
                            AccountId = 808251,
                            Amount = 1m,
                            DateTime = new DateTime(2020, 12, 28, 13, 9, 1, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("d5c26f52-219f-4e26-b84d-68d1cb04fdac")
                        },
                        new
                        {
                            Id = 55,
                            AccountId = 808251,
                            Amount = 4133.56m,
                            DateTime = new DateTime(2021, 3, 4, 14, 32, 23, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("459051e6-9c1a-4272-988e-6fc0162c2879")
                        },
                        new
                        {
                            Id = 56,
                            AccountId = 808251,
                            Amount = 10m,
                            DateTime = new DateTime(2021, 3, 30, 15, 50, 42, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("98698da6-7822-4f07-a735-6b9d4de4a8a4")
                        },
                        new
                        {
                            Id = 57,
                            AccountId = 808251,
                            Amount = 10m,
                            DateTime = new DateTime(2021, 3, 30, 16, 5, 7, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("a5b6c10f-165f-457d-acd2-afe87f5296f5")
                        });
                });

            modelBuilder.Entity("Balance.Storage.Records.AccrualRecord", b =>
                {
                    b.HasOne("Balance.Storage.Records.AccountRecord", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Balance.Storage.Records.HistoryAmountRecord", b =>
                {
                    b.HasOne("Balance.Storage.Records.AccrualRecord", "Accrual")
                        .WithMany()
                        .HasForeignKey("AccrualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accrual");
                });

            modelBuilder.Entity("Balance.Storage.Records.PaymentRecord", b =>
                {
                    b.HasOne("Balance.Storage.Records.AccountRecord", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
